#!/usr/bin/env bash
# scripts/memory-health-sweep.sh
# The recurring (2-day) local sweep over both agent-memory stores. Runs where
# both stores are actually visible - the workstation; CI and cloud runners
# cannot see the operator store or the gitignored events/, so this sweep is
# the only complete health surface.
#
# Contract:
# - Report-only toward the stores' content: it never edits memories and never
#   regenerates an index. Its only writes are (a) one idempotent HEALTH.md
#   overwrite per store and (b) a snapshot commit+push of the operator-memory
#   backup repo - the one sanctioned scheduled writer, targeting a dedicated
#   repo with no PRs and no shared history. An empty diff produces no commit.
# - Attention surfacing: a desktop notification (macOS osascript, when
#   present) fires only when the report changed since the last sweep AND
#   carries failures or warnings - new findings, not a 48-hour recital of
#   known ones. On systems without osascript the notification is skipped and
#   the exit code still carries the result.
#
# Intended trigger: launchd StartInterval 172800 (templates/launchd.plist.template)
# or a systemd user timer (templates/systemd-user.{service,timer}.template),
# or run manually at any time.
#
# Configuration (environment):
#   MEMORY_SWEEP_REPO            repo root holding scripts/ and the agent
#                                store; defaults to this script's parent dir
#   MEMORY_SWEEP_OPERATOR_STORE  path to the operator memory store (REQUIRED -
#                                it lives outside the repo, in the operator's
#                                home, so there is no portable default)
#   MEMORY_SWEEP_AGENT_STORE     path to the agent memory store; defaults to
#                                $REPO/.claude/agent-memory/agent
#   MEMORY_SWEEP_GIT_NAME        commit author name for the snapshot commit;
#   MEMORY_SWEEP_GIT_EMAIL       both set -> used as -c overrides, otherwise
#                                the store's own git config identity applies

set -uo pipefail
IFS=$'\n\t'

# launchd starts jobs with a bare PATH that misses Homebrew/local bins;
# prepend them so ripgrep is visible to the health runs below. The rg gate
# inside memory-health.sh remains the fail-closed authority - this line only
# keeps the scheduled sweep from tripping it on every fire.
PATH="/opt/homebrew/bin:/usr/local/bin:$PATH"

# Pin collation so sweep output and HEALTH.md diffs are locale-independent.
export LC_ALL=C

SCRIPT_DIR=$(cd "$(dirname "$0")" && pwd)
REPO="${MEMORY_SWEEP_REPO:-$(cd "$SCRIPT_DIR/.." && pwd)}"
OPERATOR_STORE="${MEMORY_SWEEP_OPERATOR_STORE:-}"
[ -n "$OPERATOR_STORE" ] || { echo "memory-health-sweep: MEMORY_SWEEP_OPERATOR_STORE is unset - point it at the operator memory store (it lives outside the repo, so there is no default)"; exit 2; }
AGENT_STORE="${MEMORY_SWEEP_AGENT_STORE:-$REPO/.claude/agent-memory/agent}"
HEALTH="$REPO/scripts/memory-health.sh"

[ -x "$HEALTH" ] || { echo "memory-health-sweep: $HEALTH missing or not executable"; exit 2; }

worst=0
notify_lines=""

run_store() { # $1=profile $2=store $3=extra-args...
  profile="$1"; store="$2"; shift 2
  new=$(mktemp)
  {
    printf 'Generated by scripts/memory-health-sweep.sh on %s\n\n' "$(date '+%Y-%m-%d %H:%M %Z')"
    "$HEALTH" --profile "$profile" "$store" "$@"
  } > "$new" 2>&1
  rc=$?
  [ "$rc" -gt "$worst" ] && worst=$rc
  if [ "$rc" -ge 1 ]; then
    if [ ! -f "$store/HEALTH.md" ] || ! diff -q <(tail -n +2 "$new") <(tail -n +2 "$store/HEALTH.md") > /dev/null 2>&1; then
      summary=$(tail -1 "$new")
      notify_lines="${notify_lines}${profile}: ${summary}
"
    fi
  fi
  mv "$new" "$store/HEALTH.md"
  return 0
}

run_store operator "$OPERATOR_STORE" --also-resolve "$AGENT_STORE"
run_store agent "$AGENT_STORE" --also-resolve "$OPERATOR_STORE"

# Snapshot the operator-memory backup repo (append-only history; empty diff
# commits nothing; push is skipped quietly until a remote exists). Commit
# identity comes from MEMORY_SWEEP_GIT_NAME/MEMORY_SWEEP_GIT_EMAIL when both
# are set, else from the store's own git config.
if [ -d "$OPERATOR_STORE/.git" ]; then
  git -C "$OPERATOR_STORE" add -A
  if ! git -C "$OPERATOR_STORE" diff --cached --quiet; then
    if [ -n "${MEMORY_SWEEP_GIT_NAME:-}" ] && [ -n "${MEMORY_SWEEP_GIT_EMAIL:-}" ]; then
      git -C "$OPERATOR_STORE" -c user.name="$MEMORY_SWEEP_GIT_NAME" -c user.email="$MEMORY_SWEEP_GIT_EMAIL" \
        commit -q -m "Scheduled memory snapshot ($(date '+%Y-%m-%d'))"
    else
      git -C "$OPERATOR_STORE" commit -q -m "Scheduled memory snapshot ($(date '+%Y-%m-%d'))"
    fi
  fi
  if git -C "$OPERATOR_STORE" remote get-url origin > /dev/null 2>&1; then
    git -C "$OPERATOR_STORE" push -q origin main || notify_lines="${notify_lines}backup push failed
"
  fi
fi

# macOS-only attention surface; command -v guard degrades gracefully on Linux.
if [ -n "$notify_lines" ] && command -v osascript > /dev/null 2>&1; then
  osascript -e "display notification \"$(printf '%s' "$notify_lines" | head -3 | tr '\n' ' ' | sed 's/"/\\"/g')\" with title \"memory-health sweep\"" || true
fi

printf 'sweep done: worst exit %d\n' "$worst"
exit "$worst"
