#!/usr/bin/env bash
# scripts/memory-index.sh
# Deterministic MEMORY.md generator for an agent-memory store.
#
# The index is a projection of the store, never a hand-maintained document.
# Regenerating it is idempotent: output is a pure function of the corpus.
# Each entry line is: - [<name>](<relpath>) — <description>
# with name and description taken verbatim from the file's frontmatter.
# A derived index cannot drift the way a hand-maintained dual-write does.
#
# Sort order is metadata.type group (feedback, project, reference), then
# alphabetical by filename. Deliberately NOT recency: mtime is not stable
# across clones and recency is recoverable from git log, while deterministic
# one-line diffs per added memory are not recoverable from a recency sort.
#
# Frontmatter contract (enforced by memory-health.sh, assumed here): exactly
# one single-line `name:` and one single-line `description:` per file, and a
# `type:` line (nested under `metadata:` or top-level) whose value is one of
# feedback|project|reference.
#
# Usage:
#   scripts/memory-index.sh --profile operator|agent <store-root>
#
# Profiles:
#   operator  files are <store-root>/*.md minus MEMORY.md, HEALTH.md, tmp_*
#   agent     files are <store-root>/lessons/*.md
#
# Output goes to stdout. To apply: memory-index.sh ... > <store-root>/MEMORY.md

set -Eeuo pipefail
IFS=$'\n\t'

# Pin collation: the index must be byte-identical no matter which locale the
# invoking shell carries (interactive macOS shell vs launchd vs CI runner);
# an unpinned collation drifts the sort order across locales.
export LC_ALL=C

die() { printf 'memory-index: FATAL: %s\n' "$*" >&2; exit 2; }

PROFILE="" STORE=""
while [ $# -gt 0 ]; do
  case "$1" in
    --profile) PROFILE="${2:-}"; shift 2 ;;
    -*) die "unknown option: $1" ;;
    *) STORE="$1"; shift ;;
  esac
done
[ -n "$PROFILE" ] && [ -n "$STORE" ] || die "usage: memory-index.sh --profile operator|agent <store-root>"
[ -d "$STORE" ] || die "store root not found: $STORE"

case "$PROFILE" in
  operator)
    list_files() { (cd "$STORE" && ls -- *.md 2>/dev/null) | grep -v -e '^MEMORY\.md$' -e '^HEALTH\.md$' -e '^tmp_' | sort || true; }
    rel() { printf '%s\n' "$1"; }
    header() {
      cat <<'EOF'
<!-- GENERATED by scripts/memory-index.sh - do not edit by hand.
     Regenerate: scripts/memory-index.sh --profile operator <this-dir> > MEMORY.md
     One line per memory: name and description verbatim from frontmatter.
     Sorted by type group, then filename. -->
EOF
    }
    ;;
  agent)
    list_files() { (cd "$STORE" && ls -- lessons/*.md 2>/dev/null) | sort || true; }
    rel() { printf '%s\n' "$1"; }
    header() {
      cat <<'EOF'
# agent memory index

<!-- GENERATED by scripts/memory-index.sh - do not edit by hand.
     Regenerate: scripts/memory-index.sh --profile agent .claude/agent-memory/agent > MEMORY.md -->

This file is the index for the agent's persistent project memory. It is
loaded automatically into the agent's system prompt on every invocation (first
200 lines). It is an index, not a memory: one line per lesson, name and
description taken verbatim from the lesson frontmatter, sorted by type group
then filename so each new lesson diffs as exactly one line. Recency is
recoverable from git log; deterministic diffs are not recoverable from a
recency sort. CI verifies this file byte-equals regeneration.

Layout under `.claude/agent-memory/agent/`:

- `MEMORY.md` — this generated index.
- `state.json` — tick state (last_tick_iso, tick_count, consecutive_empty_ticks).
- `events/<YYYY-MM-DD>.md` — one file per UTC day, append a section per tick.
- `lessons/<slug>.md` — durable lessons promoted from repeated patterns.

No icons. Anywhere.
EOF
    }
    ;;
  *) die "unknown profile: $PROFILE" ;;
esac

# Frontmatter block only: the lines between the leading '---' delimiters.
# A file not starting with '---' yields empty output (memory-health.sh fails
# it hard). Bounding here keeps a memory free to quote its own template
# (a fenced 'name:' line in the body) without corrupting the index.
fm() { awk 'NR==1{if($0!="---")exit; next} /^---$/{exit} {print}' "$1"; }
fm_field() { # $1=file $2=key -> first single-line value, YAML quotes stripped
  fm "$1" | sed -n "s/^$2: *//p" | head -1 | sed -E 's/^"(.*)"$/\1/; s/^'"'"'(.*)'"'"'$/\1/'
}
fm_type() { # nested metadata.type preferred, top-level tolerated
  fm "$1" | sed -n 's/^[[:space:]]*type: *//p' | head -1
}

header
for want in feedback project reference; do
  section=""
  while IFS= read -r f; do
    [ -n "$f" ] || continue
    t=$(fm_type "$STORE/$f")
    [ "$t" = "$want" ] || continue
    n=$(fm_field "$STORE/$f" name)
    d=$(fm_field "$STORE/$f" description)
    section="${section}- [${n}]($(rel "$f")) — ${d}
"
  done <<EOF
$(list_files)
EOF
  if [ -n "$section" ]; then
    printf '\n## %s\n\n%s' "$want" "$section"
  fi
done
